# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f90tUDkxtyB8VjX_eoesSBuQjpSeCKsR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("fake_bills.csv",sep = ";")

df.dropna(inplace = True)

numerical_col = ["diagonal",	"height_left","height_right",	"margin_low",	"margin_up",	"length"]

X, y = df.drop(columns = ["is_genuine"]), df["is_genuine"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 13)

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import RobustScaler
num_pipe_robust = Pipeline([
    ("scaler", RobustScaler())
])

from sklearn.compose import ColumnTransformer

preprocessor_no_transform_base = ColumnTransformer([
    ("numerical", num_pipe_robust, numerical_col)
])

from sklearn.linear_model import LogisticRegression

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state = 13)

logistic = LogisticRegression()

params = {
    "logistic__C": [0.01, 0.1, 1, 10],
    "logistic__penalty": ["l2"],
    "logistic__solver": ["lbfgs"]
}

preprocessor_logistic_no_transform = ColumnTransformer([
    ("numerical", num_pipe_robust, numerical_col)
])

pipe_logistic_no_transform = ImbPipeline([
    ("smote", SMOTE(random_state=42)),
    ("preprocessing",preprocessor_logistic_no_transform),
    ("logistic", logistic)
])

from sklearn.model_selection import GridSearchCV

grid_logistic_no_transform = GridSearchCV(pipe_logistic_no_transform, params, cv = 5, scoring = "f1", n_jobs = -1, verbose = 2)

grid_logistic_no_transform.fit(X_train, y_train)

best_logistic_no_transform = grid_logistic_no_transform.best_estimator_

y_pred_logistic_no_transform = grid_logistic_no_transform.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic_no_transform)}")
print(f"Precision : {precision_score(y_test, y_pred_logistic_no_transform, pos_label=False)}")
print(f"Recall : {recall_score(y_test, y_pred_logistic_no_transform, pos_label=False)}")
print(f"F1 Score : {f1_score(y_test, y_pred_logistic_no_transform, pos_label=False)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred_logistic_no_transform)}")
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_logistic_no_transform)
print(f"confusion matrix :\n{cm}")

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# probability of positive class
y_proba = grid_logistic_no_transform.predict_proba(X_test)[:, 0]

# ROC
fpr, tpr, thresholds = roc_curve(y_test, y_proba, pos_label=False)
roc_auc = auc(fpr, tpr)

# plot
plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate (Recall)")
plt.title("ROC Curve")
plt.legend()

plt.show()

from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc


precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_proba,
    pos_label= False
)

pr_auc = auc(recall, precision)

plt.figure()
plt.plot(recall, precision, label=f"PR AUC = {pr_auc:.3f}")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(cm,annot=True,fmt="d",cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("Actual label")
plt.title("Confusion Matrix")
plt.show()

